"""infra and gaps, project brief

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-30 19:32:12.559293+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gap_registers',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('source_state_id', sa.Uuid(), nullable=True),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('locked_by', sa.Uuid(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gap_registers')),
    sa.UniqueConstraint('project_id', 'number', name=op.f('uq_gap_registers_project_id_number'))
    )
    op.create_index(op.f('ix_gap_registers_project_id'), 'gap_registers', ['project_id'], unique=False)
    op.create_table('infra_rules',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('component', sa.String(length=20), nullable=False),
    sa.Column('lens', sa.String(length=12), nullable=False),
    sa.Column('gap_type', sa.String(length=60), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('priority_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('when', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verify_if_unknown', sa.Boolean(), nullable=False),
    sa.Column('affected_list', sa.String(length=60), nullable=True),
    sa.Column('qty_fact', sa.String(length=60), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('company_sizes', sa.ARRAY(sa.String(length=10)), nullable=False),
    sa.Column('budget_tiers', sa.ARRAY(sa.String(length=12)), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("priority IN ('high','consider')", name=op.f('ck_infra_rules_priority_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_infra_rules'))
    )
    op.create_index(op.f('ix_infra_rules_gap_type'), 'infra_rules', ['gap_type'], unique=False)
    op.create_index('uq_infra_rules_code', 'infra_rules', ['code'], unique=True)
    op.create_table('infra_states',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_import_id', sa.Uuid(), nullable=True),
    sa.Column('rule_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('locked_by', sa.Uuid(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_infra_states')),
    sa.UniqueConstraint('project_id', 'kind', 'number', name=op.f('uq_infra_states_project_id_kind_number'))
    )
    op.create_index(op.f('ix_infra_states_project_id'), 'infra_states', ['project_id'], unique=False)
    op.create_table('gaps',
    sa.Column('register_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=40), nullable=True),
    sa.Column('rule_version', sa.Integer(), nullable=True),
    sa.Column('gap_type', sa.String(length=60), nullable=False),
    sa.Column('component', sa.String(length=20), nullable=False),
    sa.Column('lens', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('affected', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('qty_hint', sa.Integer(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('last_change_reason', sa.String(length=500), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("priority IN ('high','consider')", name=op.f('ck_gaps_priority_valid')),
    sa.CheckConstraint("status IN ('open','verify','accepted','disputed','dismissed')", name=op.f('ck_gaps_status_valid')),
    sa.ForeignKeyConstraint(['register_id'], ['gap_registers.id'], name=op.f('fk_gaps_register_id_gap_registers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gaps')),
    sa.UniqueConstraint('register_id', 'number', name=op.f('uq_gaps_register_id_number'))
    )
    op.create_index(op.f('ix_gaps_gap_type'), 'gaps', ['gap_type'], unique=False)
    op.create_index(op.f('ix_gaps_register_id'), 'gaps', ['register_id'], unique=False)
    op.create_table('infra_rule_changes',
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('proposed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['infra_rules.id'], name=op.f('fk_infra_rule_changes_rule_id_infra_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_infra_rule_changes'))
    )
    op.create_index(op.f('ix_infra_rule_changes_rule_id'), 'infra_rule_changes', ['rule_id'], unique=False)
    op.create_table('project_briefs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('company_size', sa.String(length=10), nullable=False),
    sa.Column('budget_tier', sa.String(length=12), nullable=False),
    sa.Column('users_now', sa.Integer(), nullable=True),
    sa.Column('users_12m', sa.Integer(), nullable=True),
    sa.Column('sites', sa.Integer(), nullable=False),
    sa.Column('preferred_brands', sa.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('excluded_brands', sa.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('budget_ceiling', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('category_budgets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keep_assets', sa.ARRAY(sa.String(length=200)), nullable=False),
    sa.Column('compliance', sa.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_briefs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_project_briefs'))
    )
    # ---- hand-written: locked outputs never change ------------------------------------
    op.execute(
        """
        CREATE FUNCTION infra_locked_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_TABLE_NAME = 'infra_states' THEN
                IF OLD.status = 'locked' AND (TG_OP = 'DELETE' OR NEW.data IS DISTINCT FROM OLD.data
                   OR NEW.kind IS DISTINCT FROM OLD.kind OR NEW.number IS DISTINCT FROM OLD.number) THEN
                    RAISE EXCEPTION 'a locked infra state cannot change' USING ERRCODE = 'restrict_violation';
                END IF;
            ELSIF TG_TABLE_NAME = 'gap_registers' THEN
                IF OLD.status = 'locked' AND (TG_OP = 'DELETE' OR NEW.status IS DISTINCT FROM OLD.status
                   OR NEW.facts IS DISTINCT FROM OLD.facts) THEN
                    RAISE EXCEPTION 'a locked gap register cannot change' USING ERRCODE = 'restrict_violation';
                END IF;
            ELSIF TG_TABLE_NAME = 'gaps' THEN
                IF EXISTS (SELECT 1 FROM gap_registers r WHERE r.id = OLD.register_id AND r.status = 'locked') THEN
                    RAISE EXCEPTION 'gaps of a locked register cannot change' USING ERRCODE = 'restrict_violation';
                END IF;
            END IF;
            IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
            RETURN NEW;
        END $$;
        """
    )
    for table in ("infra_states", "gap_registers", "gaps"):
        op.execute(
            f"CREATE TRIGGER {table}_locked_guard_trg BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION infra_locked_guard()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in ("infra_states", "gap_registers", "gaps"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_locked_guard_trg ON {table}")
    op.execute("DROP FUNCTION IF EXISTS infra_locked_guard()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_briefs')
    op.drop_index(op.f('ix_infra_rule_changes_rule_id'), table_name='infra_rule_changes')
    op.drop_table('infra_rule_changes')
    op.drop_index(op.f('ix_gaps_register_id'), table_name='gaps')
    op.drop_index(op.f('ix_gaps_gap_type'), table_name='gaps')
    op.drop_table('gaps')
    op.drop_index(op.f('ix_infra_states_project_id'), table_name='infra_states')
    op.drop_table('infra_states')
    op.drop_index('uq_infra_rules_code', table_name='infra_rules')
    op.drop_index(op.f('ix_infra_rules_gap_type'), table_name='infra_rules')
    op.drop_table('infra_rules')
    op.drop_index(op.f('ix_gap_registers_project_id'), table_name='gap_registers')
    op.drop_table('gap_registers')
    # ### end Alembic commands ###
