"""prismsuite and catalogue

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 18:06:01.582401+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_imports',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('parser_name', sa.String(length=60), nullable=False),
    sa.Column('schema_version', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('original_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('imported_by', sa.Uuid(), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_imports'))
    )
    op.create_index(op.f('ix_audit_imports_file_id'), 'audit_imports', ['file_id'], unique=False)
    op.create_index(op.f('ix_audit_imports_project_id'), 'audit_imports', ['project_id'], unique=False)
    op.create_index('uq_audit_imports_one_approved', 'audit_imports', ['project_id'], unique=True, postgresql_where="status = 'approved'")
    op.create_index('uq_audit_imports_project_revision', 'audit_imports', ['project_id', 'revision'], unique=True)
    op.create_table('catalogue_categories',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_catalogue_categories'))
    )
    op.create_table('rejected_uploads',
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rejected_uploads'))
    )
    op.create_table('stored_files',
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('bucket', sa.String(length=63), nullable=False),
    sa.Column('object_key', sa.String(length=300), nullable=False),
    sa.Column('object_version', sa.String(length=120), nullable=True),
    sa.Column('scan_engine', sa.String(length=40), nullable=False),
    sa.Column('exif_stripped', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stored_files')),
    sa.UniqueConstraint('object_key', name=op.f('uq_stored_files_object_key'))
    )
    op.create_index(op.f('ix_stored_files_project_id'), 'stored_files', ['project_id'], unique=False)
    op.create_index(op.f('ix_stored_files_purpose'), 'stored_files', ['purpose'], unique=False)
    op.create_index(op.f('ix_stored_files_sha256'), 'stored_files', ['sha256'], unique=False)
    op.create_index(op.f('ix_stored_files_uploaded_by'), 'stored_files', ['uploaded_by'], unique=False)
    op.create_table('vendors',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('india_support', sa.Boolean(), nullable=False),
    sa.Column('preferred', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors'))
    )
    op.create_index('uq_vendors_name_active', 'vendors', [sa.literal_column('lower(name)')], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('audit_corrections',
    sa.Column('import_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('corrected_by', sa.Uuid(), nullable=False),
    sa.Column('corrected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['audit_imports.id'], name=op.f('fk_audit_corrections_import_id_audit_imports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_corrections'))
    )
    op.create_index(op.f('ix_audit_corrections_import_id'), 'audit_corrections', ['import_id'], unique=False)
    op.create_table('catalogue_items',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('inclusions', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('hsn_sac', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('stock_status', sa.String(length=12), nullable=False),
    sa.Column('alternative_item_id', sa.Uuid(), nullable=True),
    sa.Column('eol_date', sa.Date(), nullable=True),
    sa.Column('eos_date', sa.Date(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("kind IN ('product','service')", name=op.f('ck_catalogue_items_kind_valid')),
    sa.CheckConstraint("stock_status IN ('in_stock','limited','on_order','out_of_stock')", name=op.f('ck_catalogue_items_stock_status_valid')),
    sa.CheckConstraint('gst_rate >= 0 AND gst_rate <= 100', name=op.f('ck_catalogue_items_gst_rate_range')),
    sa.ForeignKeyConstraint(['alternative_item_id'], ['catalogue_items.id'], name=op.f('fk_catalogue_items_alternative_item_id_catalogue_items')),
    sa.ForeignKeyConstraint(['category'], ['catalogue_categories.code'], name=op.f('fk_catalogue_items_category_catalogue_categories')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_catalogue_items_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalogue_items'))
    )
    op.create_index(op.f('ix_catalogue_items_category'), 'catalogue_items', ['category'], unique=False)
    op.create_index(op.f('ix_catalogue_items_vendor_id'), 'catalogue_items', ['vendor_id'], unique=False)
    op.create_index('uq_catalogue_items_code', 'catalogue_items', ['code'], unique=True)
    op.create_table('catalogue_market_data',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value_text', sa.String(length=300), nullable=True),
    sa.Column('value_num', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('source_note', sa.String(length=300), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('entered_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['catalogue_items.id'], name=op.f('fk_catalogue_market_data_item_id_catalogue_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalogue_market_data'))
    )
    op.create_index(op.f('ix_catalogue_market_data_item_id'), 'catalogue_market_data', ['item_id'], unique=False)
    op.create_index('ix_market_item_key', 'catalogue_market_data', ['item_id', 'key', 'as_of'], unique=False)
    op.create_table('price_entries',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('supplier', sa.String(length=160), nullable=False),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('selling', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quoted_on', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('source_note', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('entered_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('active','superseded','expired')", name=op.f('ck_price_entries_status_valid')),
    sa.CheckConstraint('cost >= 0 AND selling >= 0', name=op.f('ck_price_entries_non_negative')),
    sa.CheckConstraint('selling >= cost', name=op.f('ck_price_entries_selling_not_below_cost')),
    sa.CheckConstraint('valid_until >= quoted_on', name=op.f('ck_price_entries_validity_after_quote')),
    sa.ForeignKeyConstraint(['item_id'], ['catalogue_items.id'], name=op.f('fk_price_entries_item_id_catalogue_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_entries'))
    )
    op.create_index('ix_price_entries_item_created', 'price_entries', ['item_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_price_entries_item_id'), 'price_entries', ['item_id'], unique=False)
    op.create_index('uq_price_entries_one_active', 'price_entries', ['item_id'], unique=True, postgresql_where="status = 'active'")
    # ---- hand-written: append-only history tables ------------------------------------
    op.execute(
        """
        CREATE FUNCTION append_only_block_changes() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only', TG_TABLE_NAME USING ERRCODE = 'restrict_violation';
        END $$;
        """
    )
    for table in ("audit_corrections", "catalogue_market_data"):
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION append_only_block_changes()"
        )
    # Price rows are history too: the only allowed change is status/ended_at, and never DELETE.
    op.execute(
        """
        CREATE FUNCTION price_entries_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'price_entries rows cannot be deleted' USING ERRCODE = 'restrict_violation';
            END IF;
            IF NEW.item_id IS DISTINCT FROM OLD.item_id OR NEW.cost IS DISTINCT FROM OLD.cost
               OR NEW.selling IS DISTINCT FROM OLD.selling OR NEW.quoted_on IS DISTINCT FROM OLD.quoted_on
               OR NEW.valid_until IS DISTINCT FROM OLD.valid_until OR NEW.supplier IS DISTINCT FROM OLD.supplier THEN
                RAISE EXCEPTION 'price_entries amounts and dates cannot be edited; add a new price'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            RETURN NEW;
        END $$;
        """
    )
    op.execute(
        "CREATE TRIGGER price_entries_guard_trg BEFORE UPDATE OR DELETE ON price_entries "
        "FOR EACH ROW EXECUTE FUNCTION price_entries_guard()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS price_entries_guard_trg ON price_entries")
    op.execute("DROP FUNCTION IF EXISTS price_entries_guard()")
    op.execute("DROP TRIGGER IF EXISTS audit_corrections_append_only ON audit_corrections")
    op.execute("DROP TRIGGER IF EXISTS catalogue_market_data_append_only ON catalogue_market_data")
    op.execute("DROP FUNCTION IF EXISTS append_only_block_changes()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_price_entries_one_active', table_name='price_entries', postgresql_where="status = 'active'")
    op.drop_index(op.f('ix_price_entries_item_id'), table_name='price_entries')
    op.drop_index('ix_price_entries_item_created', table_name='price_entries')
    op.drop_table('price_entries')
    op.drop_index('ix_market_item_key', table_name='catalogue_market_data')
    op.drop_index(op.f('ix_catalogue_market_data_item_id'), table_name='catalogue_market_data')
    op.drop_table('catalogue_market_data')
    op.drop_index('uq_catalogue_items_code', table_name='catalogue_items')
    op.drop_index(op.f('ix_catalogue_items_vendor_id'), table_name='catalogue_items')
    op.drop_index(op.f('ix_catalogue_items_category'), table_name='catalogue_items')
    op.drop_table('catalogue_items')
    op.drop_index(op.f('ix_audit_corrections_import_id'), table_name='audit_corrections')
    op.drop_table('audit_corrections')
    op.drop_index('uq_vendors_name_active', table_name='vendors', postgresql_where='deleted_at IS NULL')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_stored_files_uploaded_by'), table_name='stored_files')
    op.drop_index(op.f('ix_stored_files_sha256'), table_name='stored_files')
    op.drop_index(op.f('ix_stored_files_purpose'), table_name='stored_files')
    op.drop_index(op.f('ix_stored_files_project_id'), table_name='stored_files')
    op.drop_table('stored_files')
    op.drop_table('rejected_uploads')
    op.drop_table('catalogue_categories')
    op.drop_index('uq_audit_imports_project_revision', table_name='audit_imports')
    op.drop_index('uq_audit_imports_one_approved', table_name='audit_imports', postgresql_where="status = 'approved'")
    op.drop_index(op.f('ix_audit_imports_project_id'), table_name='audit_imports')
    op.drop_index(op.f('ix_audit_imports_file_id'), table_name='audit_imports')
    op.drop_table('audit_imports')
    # ### end Alembic commands ###
