"""boq engine

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-30 19:43:16.099536+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boq_templates',
    sa.Column('gap_type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('lines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boq_templates'))
    )
    op.create_index('uq_boq_templates_gap_type', 'boq_templates', ['gap_type'], unique=True)
    op.create_table('boqs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('stage', sa.String(length=18), nullable=False),
    sa.Column('draft', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_register_id', sa.Uuid(), nullable=True),
    sa.Column('generation_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quote_ref', sa.String(length=40), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('pricing_approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("stage IN ('drafting','pricing_review','pricing_approved')", name=op.f('ck_boqs_stage_valid')),
    sa.CheckConstraint("status IN ('draft','accepted','closed')", name=op.f('ck_boqs_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boqs')),
    sa.UniqueConstraint('quote_ref', name=op.f('uq_boqs_quote_ref'))
    )
    op.create_index('uq_boqs_project', 'boqs', ['project_id'], unique=True)
    op.create_table('company_settings',
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_company_settings'))
    )
    op.create_table('reco_weights',
    sa.Column('segment', sa.String(length=12), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('segment', name=op.f('pk_reco_weights'))
    )
    op.create_table('boq_edits',
    sa.Column('boq_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('by', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('draft_rev', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['boq_id'], ['boqs.id'], name=op.f('fk_boq_edits_boq_id_boqs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boq_edits'))
    )
    op.create_index(op.f('ix_boq_edits_boq_id'), 'boq_edits', ['boq_id'], unique=False)
    op.create_index(op.f('ix_boq_edits_by'), 'boq_edits', ['by'], unique=False)
    op.create_table('boq_versions',
    sa.Column('boq_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('quote_ref', sa.String(length=40), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('totals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_summary', sa.String(length=400), nullable=False),
    sa.Column('delta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('issued_by', sa.Uuid(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pricing_approved_by', sa.Uuid(), nullable=False),
    sa.Column('selected_options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('po_number', sa.String(length=60), nullable=True),
    sa.Column('po_date', sa.Date(), nullable=True),
    sa.Column('po_file_id', sa.Uuid(), nullable=True),
    sa.Column('accepted_by', sa.Uuid(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("state IN ('issued','accepted','superseded')", name=op.f('ck_boq_versions_state_valid')),
    sa.ForeignKeyConstraint(['boq_id'], ['boqs.id'], name=op.f('fk_boq_versions_boq_id_boqs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boq_versions')),
    sa.UniqueConstraint('boq_id', 'number', name=op.f('uq_boq_versions_boq_id_number'))
    )
    op.create_index(op.f('ix_boq_versions_boq_id'), 'boq_versions', ['boq_id'], unique=False)
    op.create_index(op.f('ix_boq_versions_project_id'), 'boq_versions', ['project_id'], unique=False)
    # ---- hand-written: issued BOQ versions are immutable -------------------------------
    op.execute(
        """
        CREATE FUNCTION boq_versions_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'issued BOQ versions cannot be deleted' USING ERRCODE = 'restrict_violation';
            END IF;
            IF OLD.state IN ('accepted', 'superseded') THEN
                RAISE EXCEPTION 'a % BOQ version cannot change', OLD.state USING ERRCODE = 'restrict_violation';
            END IF;
            -- issued: may become superseded (state only) or accepted (with the purchase order)
            IF NEW.state = OLD.state THEN
                RAISE EXCEPTION 'an issued BOQ version cannot change' USING ERRCODE = 'restrict_violation';
            END IF;
            IF NEW.state = 'superseded' AND (NEW.content IS DISTINCT FROM OLD.content OR NEW.totals IS DISTINCT FROM OLD.totals) THEN
                RAISE EXCEPTION 'superseding a BOQ version cannot change its content' USING ERRCODE = 'restrict_violation';
            END IF;
            IF NEW.quote_ref IS DISTINCT FROM OLD.quote_ref OR NEW.number IS DISTINCT FROM OLD.number
               OR NEW.boq_id IS DISTINCT FROM OLD.boq_id OR NEW.issued_by IS DISTINCT FROM OLD.issued_by THEN
                RAISE EXCEPTION 'BOQ version identity cannot change' USING ERRCODE = 'restrict_violation';
            END IF;
            RETURN NEW;
        END $$;
        """
    )
    op.execute(
        "CREATE TRIGGER boq_versions_guard_trg BEFORE UPDATE OR DELETE ON boq_versions "
        "FOR EACH ROW EXECUTE FUNCTION boq_versions_guard()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS boq_versions_guard_trg ON boq_versions")
    op.execute("DROP FUNCTION IF EXISTS boq_versions_guard()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boq_versions_project_id'), table_name='boq_versions')
    op.drop_index(op.f('ix_boq_versions_boq_id'), table_name='boq_versions')
    op.drop_table('boq_versions')
    op.drop_index(op.f('ix_boq_edits_by'), table_name='boq_edits')
    op.drop_index(op.f('ix_boq_edits_boq_id'), table_name='boq_edits')
    op.drop_table('boq_edits')
    op.drop_table('reco_weights')
    op.drop_table('company_settings')
    op.drop_index('uq_boqs_project', table_name='boqs')
    op.drop_table('boqs')
    op.drop_index('uq_boq_templates_gap_type', table_name='boq_templates')
    op.drop_table('boq_templates')
    # ### end Alembic commands ###
