"""audit import kind

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-30 19:12:06.439801+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_imports', sa.Column('kind', sa.String(length=12), server_default='baseline', nullable=False))
    op.drop_index(op.f('uq_audit_imports_one_approved'), table_name='audit_imports', postgresql_where="((status)::text = 'approved'::text)")
    op.create_index('uq_audit_imports_one_approved_per_kind', 'audit_imports', ['project_id', 'kind'], unique=True, postgresql_where="status = 'approved'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_audit_imports_one_approved_per_kind', table_name='audit_imports', postgresql_where="status = 'approved'")
    op.create_index(op.f('uq_audit_imports_one_approved'), 'audit_imports', ['project_id'], unique=True, postgresql_where="((status)::text = 'approved'::text)")
    op.drop_column('audit_imports', 'kind')
    # ### end Alembic commands ###
