"""platform identity audit customers

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 16:56:36.314526+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload_ciphertext', sa.Text(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    sa.UniqueConstraint('hash', name=op.f('uq_audit_log_hash'))
    )
    op.create_index('ix_audit_log_actor', 'audit_log', ['actor_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_log_subject_id'), 'audit_log', ['subject_id'], unique=False)
    op.create_table('audit_subject_keys',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('wrapped_key', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('shredded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shredded_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('subject_id', name=op.f('pk_audit_subject_keys'))
    )
    op.create_table('customers',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('legal_name', sa.String(length=250), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('segment', sa.String(length=20), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('address_line1', sa.String(length=250), nullable=False),
    sa.Column('address_line2', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('account_owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_account_owner_id'), 'customers', ['account_owner_id'], unique=False)
    op.create_index('uq_customers_code', 'customers', ['code'], unique=True)
    op.create_index('uq_customers_gstin_active', 'customers', ['gstin'], unique=True, postgresql_where='deleted_at IS NULL AND gstin IS NOT NULL')
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_feature_flags'))
    )
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=80), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys')),
    sa.UniqueConstraint('scope', 'key', name=op.f('uq_idempotency_keys_scope_key'))
    )
    op.create_index(op.f('ix_idempotency_keys_expires_at'), 'idempotency_keys', ['expires_at'], unique=False)
    op.create_table('number_sequences',
    sa.Column('scope', sa.String(length=120), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('scope', name=op.f('pk_number_sequences'))
    )
    op.create_table('outbox_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('subscriber', sa.String(length=120), nullable=False),
    sa.Column('event', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_messages'))
    )
    op.create_index('ix_outbox_due', 'outbox_messages', ['status', 'available_at'], unique=False)
    op.create_index(op.f('ix_outbox_messages_event_id'), 'outbox_messages', ['event_id'], unique=False)
    op.create_index(op.f('ix_outbox_messages_event_type'), 'outbox_messages', ['event_type'], unique=False)
    op.create_table('stage_gate_configs',
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('approver_roles', sa.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('artifact_type', sa.String(length=60), nullable=True),
    sa.Column('requires_artifact', sa.Boolean(), nullable=False),
    sa.Column('requires_customer_ack', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('stage', name=op.f('pk_stage_gate_configs'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('initials', sa.String(length=6), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret_enc', sa.Text(), nullable=True),
    sa.Column('mfa_pending_secret_enc', sa.Text(), nullable=True),
    sa.Column('mfa_last_used_step', sa.Integer(), nullable=True),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('lockouts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_customer_id'), 'users', ['customer_id'], unique=False)
    op.create_index('uq_users_email_active', 'users', ['email'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('mfa_verified', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=60), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions'))
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('customer_sites',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address_line1', sa.String(length=250), nullable=False),
    sa.Column('address_line2', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_sites_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_sites'))
    )
    op.create_index(op.f('ix_customer_sites_customer_id'), 'customer_sites', ['customer_id'], unique=False)
    op.create_table('mfa_recovery_codes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mfa_recovery_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mfa_recovery_codes')),
    sa.UniqueConstraint('user_id', 'code_hash', name=op.f('uq_mfa_recovery_codes_user_id_code_hash'))
    )
    op.create_index(op.f('ix_mfa_recovery_codes_user_id'), 'mfa_recovery_codes', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role', name=op.f('pk_user_roles'))
    )
    op.create_table('customer_contacts',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('can_sign_off', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_contacts_customer_id_customers')),
    sa.ForeignKeyConstraint(['site_id'], ['customer_sites.id'], name=op.f('fk_customer_contacts_site_id_customer_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_contacts'))
    )
    op.create_index(op.f('ix_customer_contacts_customer_id'), 'customer_contacts', ['customer_id'], unique=False)
    op.create_table('projects',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_stage', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_projects_customer_id_customers')),
    sa.ForeignKeyConstraint(['site_id'], ['customer_sites.id'], name=op.f('fk_projects_site_id_customer_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_customer_id'), 'projects', ['customer_id'], unique=False)
    op.create_index('uq_projects_code', 'projects', ['code'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['auth_sessions.id'], name=op.f('fk_refresh_tokens_session_id_auth_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_role', sa.String(length=40), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_members_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id', name=op.f('pk_project_members'))
    )
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('stage_artifacts',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('artifact_type', sa.String(length=60), nullable=False),
    sa.Column('artifact_id', sa.String(length=80), nullable=False),
    sa.Column('artifact_version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('locked_by', sa.Uuid(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_stage_artifacts_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_artifacts')),
    sa.UniqueConstraint('project_id', 'artifact_type', 'artifact_id', 'artifact_version', name=op.f('uq_stage_artifacts_project_id_artifact_type_artifact_id_artifact_version')),
    sa.UniqueConstraint('source_event_id', name=op.f('uq_stage_artifacts_source_event_id'))
    )
    op.create_index(op.f('ix_stage_artifacts_project_id'), 'stage_artifacts', ['project_id'], unique=False)
    op.create_table('stage_submissions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('artifact_id', sa.Uuid(), nullable=True),
    sa.Column('requires_customer_ack', sa.Boolean(), nullable=False),
    sa.Column('customer_ack_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['stage_artifacts.id'], name=op.f('fk_stage_submissions_artifact_id_stage_artifacts')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_stage_submissions_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_submissions'))
    )
    op.create_index(op.f('ix_stage_submissions_project_id'), 'stage_submissions', ['project_id'], unique=False)
    op.create_index('uq_stage_submissions_pending', 'stage_submissions', ['project_id', 'stage'], unique=True, postgresql_where="status = 'pending'")
    op.create_table('customer_acks',
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_by', sa.Uuid(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_name', sa.String(length=200), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['customer_contacts.id'], name=op.f('fk_customer_acks_contact_id_customer_contacts')),
    sa.ForeignKeyConstraint(['submission_id'], ['stage_submissions.id'], name=op.f('fk_customer_acks_submission_id_stage_submissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_acks')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_customer_acks_token_hash'))
    )
    op.create_index(op.f('ix_customer_acks_submission_id'), 'customer_acks', ['submission_id'], unique=False)
    op.create_table('gate_decisions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=False),
    sa.Column('decided_by_name', sa.String(length=200), nullable=False),
    sa.Column('decided_by_roles', sa.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('artifact_type', sa.String(length=60), nullable=True),
    sa.Column('artifact_ref', sa.String(length=80), nullable=True),
    sa.Column('artifact_version', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_gate_decisions_project_id_projects')),
    sa.ForeignKeyConstraint(['submission_id'], ['stage_submissions.id'], name=op.f('fk_gate_decisions_submission_id_stage_submissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gate_decisions')),
    sa.UniqueConstraint('submission_id', name=op.f('uq_gate_decisions_submission_id'))
    )
    op.create_index(op.f('ix_gate_decisions_project_id'), 'gate_decisions', ['project_id'], unique=False)
    # ---- hand-written: audit log is append-only -------------------------------------
    op.execute(
        """
        CREATE FUNCTION audit_log_block_changes() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only (% blocked)', TG_OP
                USING ERRCODE = 'insufficient_privilege';
        END $$;
        """
    )
    op.execute(
        "CREATE TRIGGER audit_log_no_update_delete BEFORE UPDATE OR DELETE ON audit_log "
        "FOR EACH ROW EXECUTE FUNCTION audit_log_block_changes()"
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'p1_app') THEN
                REVOKE UPDATE, DELETE, TRUNCATE ON audit_log FROM p1_app;
                REVOKE UPDATE, DELETE, TRUNCATE ON gate_decisions FROM p1_app;
            END IF;
        END $$;
        """
    )
    op.execute("REVOKE UPDATE, DELETE, TRUNCATE ON audit_log FROM PUBLIC")

    # ---- hand-written: default stage gates ------------------------------------------
    gates = sa.table(
        "stage_gate_configs",
        sa.column("stage", sa.String),
        sa.column("approver_roles", sa.ARRAY(sa.String)),
        sa.column("artifact_type", sa.String),
        sa.column("requires_artifact", sa.Boolean),
        sa.column("requires_customer_ack", sa.Boolean),
        sa.column("version", sa.Integer),
    )
    op.bulk_insert(
        gates,
        [
            {"stage": "audit_intake", "approver_roles": ["solution_architect", "technical_lead"], "artifact_type": "prismsuite_audit", "requires_artifact": True, "requires_customer_ack": False, "version": 1},
            {"stage": "current_infra", "approver_roles": ["solution_architect", "technical_lead"], "artifact_type": "infra_current", "requires_artifact": True, "requires_customer_ack": False, "version": 1},
            {"stage": "ideal_infra", "approver_roles": ["solution_architect", "technical_lead"], "artifact_type": "infra_ideal", "requires_artifact": True, "requires_customer_ack": False, "version": 1},
            {"stage": "gap_analysis", "approver_roles": ["director", "solution_architect"], "artifact_type": "gap_register", "requires_artifact": True, "requires_customer_ack": True, "version": 1},
            {"stage": "boq", "approver_roles": ["director", "sales_head"], "artifact_type": "boq_version", "requires_artifact": True, "requires_customer_ack": False, "version": 1},
            {"stage": "implementation_plan", "approver_roles": ["project_manager", "technical_lead"], "artifact_type": "implementation_plan", "requires_artifact": True, "requires_customer_ack": False, "version": 1},
            {"stage": "field_work", "approver_roles": ["technical_lead"], "artifact_type": "field_work_summary", "requires_artifact": True, "requires_customer_ack": False, "version": 1},
            {"stage": "completion", "approver_roles": ["director"], "artifact_type": "completion_report", "requires_artifact": True, "requires_customer_ack": True, "version": 1},
        ],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_update_delete ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_block_changes()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gate_decisions_project_id'), table_name='gate_decisions')
    op.drop_table('gate_decisions')
    op.drop_index(op.f('ix_customer_acks_submission_id'), table_name='customer_acks')
    op.drop_table('customer_acks')
    op.drop_index('uq_stage_submissions_pending', table_name='stage_submissions', postgresql_where="status = 'pending'")
    op.drop_index(op.f('ix_stage_submissions_project_id'), table_name='stage_submissions')
    op.drop_table('stage_submissions')
    op.drop_index(op.f('ix_stage_artifacts_project_id'), table_name='stage_artifacts')
    op.drop_table('stage_artifacts')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_refresh_tokens_session_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('uq_projects_code', table_name='projects')
    op.drop_index(op.f('ix_projects_customer_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_customer_contacts_customer_id'), table_name='customer_contacts')
    op.drop_table('customer_contacts')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_mfa_recovery_codes_user_id'), table_name='mfa_recovery_codes')
    op.drop_table('mfa_recovery_codes')
    op.drop_index(op.f('ix_customer_sites_customer_id'), table_name='customer_sites')
    op.drop_table('customer_sites')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index('uq_users_email_active', table_name='users', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_users_customer_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('stage_gate_configs')
    op.drop_index(op.f('ix_outbox_messages_event_type'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_event_id'), table_name='outbox_messages')
    op.drop_index('ix_outbox_due', table_name='outbox_messages')
    op.drop_table('outbox_messages')
    op.drop_table('number_sequences')
    op.drop_index(op.f('ix_idempotency_keys_expires_at'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_table('feature_flags')
    op.drop_index('uq_customers_gstin_active', table_name='customers', postgresql_where='deleted_at IS NULL AND gstin IS NOT NULL')
    op.drop_index('uq_customers_code', table_name='customers')
    op.drop_index(op.f('ix_customers_account_owner_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('audit_subject_keys')
    op.drop_index(op.f('ix_audit_log_subject_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index('ix_audit_log_actor', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
